name: Docker Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: update code
        run: sudo apt update && sudo apt upgrade -y
      - name: check uptime
        run: uptime

      - name: Build Docker image
        run: docker build -t hello-world-python .
      
      - name: install nginx
        run: sudo apt install nginx